"""initial

Revision ID: 5657a4a80d13
Revises: b9c4aa341f19
Create Date: 2023-03-14 16:57:35.137255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5657a4a80d13'
down_revision = 'b9c4aa341f19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('status', sa.Enum('draft', 'pending', 'finished', 'failed', name='statusenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'status')
    # ### end Alembic commands ###
