"""migration_2

Revision ID: 5acf354c8d6e
Revises: 5657a4a80d13
Create Date: 2023-03-14 17:15:49.126094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5acf354c8d6e'
down_revision = '5657a4a80d13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
